apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deloyment
  namespace: {{ .Values.namespace }}
  labels:
    app: sound-sphere-auth
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sound-sphere-auth
  template:
    metadata:
      labels:
        app: sound-sphere-auth
    spec:
      containers:
        - name: sound-sphere-auth
          image: nachappr/sound-sphere-auth
          livenessProbe: {{ toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe: {{ toYaml .Values.readinessProbe | nindent 12 }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
            - secretRef:
                name: {{ .Chart.Name }}-secrets
            - configMapRef:
                name: {{ .Chart.Name }}-config

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: sound-sphere-auth
  ports:
    - name: {{ .Values.service.name }}
      protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
